name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.actor }}
          outputs: dist/github-contribution-grid-snake.svg

      - name: Setup Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Push Snake to Output Branch
        run: |
          git checkout --orphan output
          git --work-tree=dist add --all
          git --work-tree=dist commit -m "Generate contribution grid snake"
          git push origin HEAD:output --force
