name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: your-username
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake to Output Branch
        run: |
          git config --global user.email "theTrackSuitDev@users.noreply.github.com"
          git config --global user.name "theTrackSuitDev"
          git checkout --orphan output
          git --work-tree=dist add --all
          git --work-tree=dist commit -m "Generate contribution grid snake"
          git push origin HEAD:output --force
